# Disable Azure DevOps triggers
trigger: none

# Enable GitHub pull request trigger
pr:
  paths:
    exclude:
    - README.md

variables:
- group: CI-Tokens

steps:
- pwsh: |
    Install-Module -Name Pester -SkipPublisherCheck -Scope CurrentUser -RequiredVersion "5.3.0" -Force
    ./_TestAll.ps1 `
      -Platform "AzureDevOps" `
      -Project "PSGitLab" `
      -GitRepo "PSGitLab" `
      -Uri "https://dev.azure.com/olljanat" `
      -PlainTextPAT "$(CI_AZURE_DEVOPS_TOKEN)"
  displayName: Run Pester
  workingDirectory: '$(Build.SourcesDirectory)'
