# Disable Azure DevOps triggers
trigger: none

# Enable GitHub pull request trigger
pr:
  paths:
    exclude:
    - README.md

variables:
- group: CI-Tokens

steps:
- pwsh: |
    Install-Module -Name Pester -SkipPublisherCheck -Scope CurrentUser -RequiredVersion "5.3.0" -Force

    # FixMe: Target should be to use common version on here when possible
    # Install-Module -Name AzurePipelinesPS -Scope CurrentUser -RequiredVersion "4.0.7" -Force

    Install-Module -Name PowerShellForGitHub -Scope CurrentUser -RequiredVersion "0.16.0" -Force
    ./_TestAll.ps1 -PlainTextPAT "$(CI_AZURE_DEVOPS_TOKEN)"
  displayName: Run Pester
  workingDirectory: '$(Build.SourcesDirectory)'
