name: PR-Validate
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        shell: pwsh
        env:
          CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        run: |
          Install-Module -Name Pester -SkipPublisherCheck -Scope CurrentUser -RequiredVersion "5.3.0" -Force

          # FixMe: Target should be to use common version on here when possible
          # Install-Module -Name AzurePipelinesPS -Scope CurrentUser -RequiredVersion "4.0.7" -Force

          Install-Module -Name PowerShellForGitHub -Scope CurrentUser -RequiredVersion "0.16.0" -Force
          ./_TestAll.ps1 `
            -Platform "GitHub" `
            -Project "PSGitLab" `
            -GitRepo "PSGitLab" `
            -Uri "https://github.com" `
            -PlainTextPAT "$env:CI_GITHUB_TOKEN"
